### ISSUE TITLE
Bkank page after lines bulk delete

### ISSUE THREAD

**Issue by mhicauber** [afimb/chouette2#12]
On the  "Données > Ligne" screen : 

- Check "Activer la sélection multiple" (bulk select)
- Select one or several lines
- Click "Supprimer les lignes" delete link

=> redirected to a blank page.

(Thanks for the great work)

**Comment by brunto** [comment]
Fix in develop branch 47d2c2903f90796dc98c981b162204b55d77b910
Thank you for reporting.
