### ISSUE TITLE
Run Chouette2 fails

### ISSUE THREAD

**Issue by ilarimikkonen** [afimb/chouette2#25]
Hi,

following these instructions: https://github.com/afimb/chouette2/blob/master/INSTALL.md

this fails: RAILS_ENV=production bundle exec rails server

changes made: 
production.rb : config.serve_static_files = true (due to failure)
ruby version 2.2.10 (bundle install would not work otherwise)

ilari@scrappy:~/GTFS/chouette2$ RAILS_ENV=production bundle exec rails server
=> Booting WEBrick
=> Rails 4.2.7.1 application starting in production on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
DEPRECATION WARNING: Core extensions are deprecated and will be removed in Squeel 2.0. (called from /home/ilari/GTFS/chouette2/config/initializers/squeel.rb:5:in `block in <top (required)>')
Exiting
/home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require': /home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:27: syntax error, unexpected '.' (SyntaxError)
          status: d['status']&.downcase&.to_sym,
                               ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:29: syntax error, unexpected tLABEL, expecting '='
          count_warning: d['check_point_warning_count'].to_i,
                        ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:30: syntax error, unexpected tLABEL, expecting '='
          check_point_errors: d['check_point_errors']
                             ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:31: syntax error, unexpected '}', expecting keyword_end
        }.tap{ |hash|
         ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:48: syntax error, unexpected '.'
          status: d['status']&.downcase&.to_sym,
                               ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:50: syntax error, unexpected tLABEL, expecting '='
          count_warning: d['check_point_warning_count'].to_i,
                        ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:51: syntax error, unexpected tLABEL, expecting '='
          check_point_errors: d['check_point_errors']
                             ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:52: syntax error, unexpected '}', expecting keyword_end
        }.tap{ |hash|
         ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:74: syntax error, unexpected '.'
          status: d['status']&.downcase&.to_sym,
                               ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:76: syntax error, unexpected tLABEL, expecting '='
          count_warning: d['check_point_warning_count'].to_i,
                        ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:77: syntax error, unexpected tLABEL, expecting '='
          check_point_errors: d['check_point_errors']
                             ^
/home/ilari/.rvm/gems/ruby-2.2.10/gems/ievkit_views-0.2.2/app/services/ievkit_views/action_report.rb:78: syntax error, unexpected '}', expecting keyword_end
        }.tap{ |hash|
         ^
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:317:in `depend_on'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/engine.rb:471:in `each'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/engine.rb:471:in `block in eager_load!'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/engine.rb:469:in `each'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/engine.rb:469:in `eager_load!'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/engine.rb:346:in `eager_load!'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:56:in `each'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/ilari/.rvm/rubies/ruby-2.2.10/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/ilari/.rvm/rubies/ruby-2.2.10/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/ilari/.rvm/rubies/ruby-2.2.10/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/ilari/.rvm/rubies/ruby-2.2.10/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/ilari/.rvm/rubies/ruby-2.2.10/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/ilari/.rvm/rubies/ruby-2.2.10/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/ilari/.rvm/rubies/ruby-2.2.10/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/ilari/.rvm/rubies/ruby-2.2.10/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/ilari/.rvm/rubies/ruby-2.2.10/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /home/ilari/GTFS/chouette2/config/environment.rb:5:in `<top (required)>'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/ilari/GTFS/chouette2/config.ru:3:in `block in <main>'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
	from /home/ilari/GTFS/chouette2/config.ru:in `new'
	from /home/ilari/GTFS/chouette2/config.ru:in `<main>'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/rack-1.6.5/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/rack-1.6.5/lib/rack/server.rb:208:in `app'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/commands/server.rb:61:in `app'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/rack-1.6.5/lib/rack/server.rb:336:in `wrapped_app'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/rack-1.6.5/lib/rack/server.rb:272:in `start'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/commands/server.rb:80:in `start'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/ilari/GTFS/chouette2/bin/rails:9:in `require'
	from /home/ilari/GTFS/chouette2/bin/rails:9:in `<top (required)>'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
	from /home/ilari/.rvm/gems/ruby-2.2.10/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/ilari/GTFS/chouette2/bin/spring:13:in `require'
	from /home/ilari/GTFS/chouette2/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by ilarimikkonen** [comment]
also running RAILS_ENV=production bundle exec rake db:migrate

gives this (not sure if related):

DEPRECATION WARNING: Core extensions are deprecated and will be removed in Squeel 2.0. (called from /home/ilari/GTFS/chouette2/config/initializers/squeel.rb:5:in `block in <top (required)>')
        [WARNING] - The list of tenants to migrate appears to be empty. This could mean a few things:

          1. You may not have created any, in which case you can ignore this message
          2. You've run `apartment:migrate` directly without loading the Rails environment
            * `apartment:migrate` is now deprecated. Tenants will automatically be migrated with `db:migrate`

        Note that your tenants currently haven't been migrated. You'll need to run `db:migrate` to rectify this.

**Comment by metienne** [comment]
install instructions seem to be a 'bit' out of date;
use V3_4 branch and not master one 
use ruby version 2.3.3; it is the version used on docker images.

docker images are here : https://hub.docker.com/u/afimb/ 
use 'latest' version of them

**Comment by ilarimikkonen** [comment]
\o/ that helped. Problem solved. Merci. System is up and running.

**Comment by ilarimikkonen** [comment]
this can be closed from my perspective
