### ISSUE TITLE
GTFS export incomplete due to missing agency.txt file

### ISSUE THREAD

**Issue by ilarimikkonen** [afimb/chouette2#27]
This might be that I don't understand how the system works, but I could not find an answer in the documentation via git. I assumed that if I have filled in the company details, this would generate needed data for agency.txt file

So far I've been able to export routes data only.

environment:
both SaaS (http://appli.chouette.mobi) and own deployment (ver 3.4.1)

how to repro:
Go to exports. Some data is entered via UI to have some data to export
click "new export"
select GTFS
leave "all" as export option from drop down
select some dates, or leave as is
run the export

expected:
export runs and returns GTFS export with agency.txt in zip file

actual results:
export is done, but no meaningful data is in zip file

other:
- link to a failing job: http://appli.chouette.mobi/chouette2/referentials/5447/exports/12261/compliance_check
- this issue could belong to chouette since it seems that export / import is done on java side, but it manifests on the UI so I opened it here

**Comment by metienne** [comment]
to export any data, you need to define almost one vehicle journey on one valid timetable; because export filter on intersection between export period and timetables .
if no vehicle journey is found on the export period, an empty file is produced.

**Comment by ilarimikkonen** [comment]
ok, thanks! Now I got the export working on some cases
[smalldataTre_WORKS.zip](https://github.com/afimb/chouette2/files/2619718/smalldataTre_WORKS.zip)
this dataset is minimal and works on the saas version (3.4.2)

from my perspective you can close this
